- name: Test SSH Connection
  env:
    PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
    HOST: ${{ secrets.AWS_HOST }}
    USER: ubuntu
  run: |
    echo "$PRIVATE_KEY" > private_key.pem
    chmod 600 private_key.pem
    ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "echo 'SSH Connection Successful'"
