name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug SSH Connection
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          HOST: ${{ secrets.AWS_HOST }}
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -vvv -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "echo 'SSH Connection Successful'"

      - name: Deploy to AWS EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          HOST: ${{ secrets.AWS_HOST }}
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
            set -e  # Exit on error
            echo "Starting deployment on EC2..."
            cd /home/ubuntu/fastapi-book-project || exit 1

            # stop the fast api service and kill any current gunicorn
            sudo systemctl stop fastapi || true
            sudo pkill -f gunicorn || true

            # reload system and restart nginx
            sudo systemctl daemon-reload || true
            sudo systemctl restart nginx || true

            # pull the latest code and install dependencies


            
            git pull origin main || exit 1
            source env/bin/activate || exit 1
            pip install -r requirements.txt || exit 1

            # Restart fastapi service
            sudo systemctl start fastapi || exit 1
            
            echo "Deployment successful!"
          EOF


